# Generated by Django 6.1 on 2026-09-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsmodel',
            name='banner',
            field=models.ImageField(default='defaults/default_banner.webp', upload_to='images/'),
        ),
    ]
